//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketing.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_movie_ticketingEntities : DbContext
    {
        public db_movie_ticketingEntities()
            : base("name=db_movie_ticketingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<customerInfo> customerInfo { get; set; }
        public DbSet<empInfo> empInfo { get; set; }
        public DbSet<movieShows> movieShows { get; set; }
        public DbSet<movieTicketing> movieTicketing { get; set; }
        public DbSet<payment> payment { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
