//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketing.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class empInfo
    {
        public empInfo()
        {
            this.payment = new HashSet<payment>();
        }
    
        public int empId { get; set; }
        public string empName { get; set; }
        public string empAddress { get; set; }
        public string empRole { get; set; }
    
        public virtual ICollection<payment> payment { get; set; }
    }
}
