//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketing.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int paymentId { get; set; }
        public decimal amount { get; set; }
        public int custId { get; set; }
        public int movieId { get; set; }
        public int empId { get; set; }
    
        public virtual customerInfo customerInfo { get; set; }
        public virtual empInfo empInfo { get; set; }
    }
}
