//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketing.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_empList
    {
        public int Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Address { get; set; }
        public string Role { get; set; }
    }
}
