//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketing.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_list_movieShows
    {
        public int Movie_ID { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public string Showing_Date { get; set; }
        public string Time_Slot { get; set; }
    }
}
